### ISSUE TITLE
Null safety is needed.

### ISSUE THREAD

**Issue by Farer** [rinukkusu/simple_moment#25]
Could you update it ?

**Comment by guopeng1994** [comment]
already added

**Comment by rinukkusu** [comment]
Hi, I've integrated your changes - live in 1.1.0! Thanks for checking!

**Comment by Farer** [comment]
> Hi, I've integrated your changes - live in 1.1.0! Thanks for checking!

Good job ! Thanks !

**Comment by guopeng1994** [comment]
nice!!!!! haha
