### ISSUE TITLE
Missing features from JS

### ISSUE THREAD

**Issue by DanielSeldura** [rinukkusu/simple_moment#31]
Moment().week
and Moment.isBeforeOrCurrent and variants are not present in the current iteration, currently using implementations from DateTime to handle the gap in the meantime

**Comment by rinukkusu** [comment]
Sorry, for this very late reply! If you find the time, please make a pull request with the features you want to see in this library! Since I'm not using Dart at work anymore, I don't find the time to add a whole lot of features to my Dart projects in my freetime. 😢
