### ISSUE TITLE
Format tokens?

### ISSUE THREAD

**Issue by qasim90** [rinukkusu/simple_moment#32]
What format token are supported to show a date/time in a a specific format? Can't find anything in the readme or docs. Would be awesome if all Moment.js formatting is applicable here as well.

**Comment by rinukkusu** [comment]
We're using [the `intl` package](https://pub.dev/packages/intl) for the `format(...)` call. You can find more information in their docs: https://pub.dev/documentation/intl/latest/intl/DateFormat-class.html
